---
# These must be ordered by priority
:queues:
  - default
  - mailers
  - easy_car_production_active_storage_analysis
  - active_storage_analysis
  - easy_car_production_mailers
  - active_storage_purge