---
# These must be ordered by priority
production:
  :queues:
    - default
    - mailers
    - easy_car_production_active_storage_analysis
    - active_storage_analysis
    - easy_car_production_mailers